---
title: "Research intern"
subtitle: "Research internship in Digital Dairy Management"
execute:
  eval: false
categories:
  - Intern
  - Open
  - Cornell University
authors: Miel Hostens
date: 10/18/24
toc: false

---

## Description

The Cornell Internship Program in Digital Dairy Management and Data Analytics is committed to investing in the development of future data scientists and bio-informatici through a limited term internship experience. The intention of the internship is to give the intern an experience of learning. It offers an opportunity to gain practical insights into the field of Digital Dairy Management and Data Analytics. This experience equips interns with skills that are essential for professional practice. The knowledge and skills acquired during this internship are valuable for the intern's ongoing studies and future career.

The primary goal of this internship is to continue earlier work performed at the lab on digital twins for dairy cows. This will be achieved by learning new programming skills related to data science in the field of animal science. The aim of the project is to upgrade the digital twin model to effectively mirror the health, well-being, and productivity of individual cows. This will be facilitated through collaboration and acquiring new skills from multiple experts in the fields of data science, veterinary medicine, and sensor technology.

## Expected phases and/or goals

### Orientation

The intern is expected to actively engage by listening attentively, asking questions, and being respectful of the individuals those they encounter. The aim is for the intern to develop familiarity and confidence in navigating the work environment, and interacting with colleagues.

### Cultural orientation.

As it is expected that many interns will be from foreign countries, some orientation to American culture per se is useful.  Much of this will come from the intern’s living situation (campus housing, roommates, etc.). The Cornell community is overloaded with lectures, plays, musical events, etc., and the participant will be able to experience any of these, per their interest.

### Learning goals and objectives for the intern during the training program.

The overarching goal is for the intern to develop and practice research skills as might be utilized in future advanced studies in a career in applied bio-informatics, data science, animal and/or dairy sciene. This internship assignment provides the intern with an opportunity to learn in a professional setting. By participating in the internship, the intern gains the chance to engage with field experts, and learning from their expertise. 

Additionally, interns will further develop their critical thinking and communication skills, reading in English, interpreting experimental procedures from written protocols, and their ability to ask research questions. Most of these skills are obtained from ongoing conversations and evaluations with Dr. Hostens and his graduate students and research staff, a process that continues through the entirety of the internship.

### Role of the intern.

The overall role of the intern is to be eager, aware, proactive, and supportive of the program we will jointly develop. During the internship, the intern will focus on the project. This will be achieved by learning new programming skills, understanding algorithms, analyzing data, and drawing conclusions from it. The intern also needs to document their work, preferentially through github, give a final presentation, and if requested write a report. It's important for the intern to keep their data organized and make sure the plans are realistic. Additionally, strong teamwork and effective communication skills are key factors in their success.

### Evaluation.

How will acquisition of skills be evaluated? 

Skills acquisition will be evaluated through both a mid-term and a final evaluation.

The mid-term evaluation meeting will be scheduled in the first half of the internship. This meeting encompasses discussions about the progress of the project, advancements in the internship report, and personal growth. This meeting will include Dr, Hostens, the intern. Dr. Hostens will also complete an evaluation form, offering feedback essential for the intern's progression. It is expected that the intern will actively engage with this feedback to facilitate further development.

At the end of the internship Dr. Hostens will conduct a final assessment of the practical work delivered by the intern. This assessment will be signed and graded, serving as a comprehensive evaluation of the intern's performance.

During the internship, the intern will keep track of how the project is going and note any difficulties they encounter. This helps the intern to make progress in developing skills and knowledge. The intern will also make an report about the project and give a final presentation.

These evaluation processes are fundamental to monitoring and assessing the intern's progress, ensuring they acquire necessary skills and meet the internship program's objectives effectively.

Additional information can be requested at [miel.hostens@cornell.edu](mailto:miel.hostens@cornell.edu)

