---
title: "Meike van Leerdam"
categories:
  - MSC
  - LSTM
  - Veterinairy medicine
author: "Meike van Leerdam"
date: 09/13/2024
format: html
editor: visual
---

### Who am I:

Hi! My name is Meike, and I’m from the Netherlands. I’m currently studying Veterinary Medicine at Utrecht University, and in January, I hope to begin a PhD at Cornell University. My research will combine two of my passions: cows and data. Although I still have much to learn, I enjoy programming, as it feels like solving puzzles. Thanks to my veterinary background, I’ve spent considerable time caring for cows and working to improve their welfare, which is something I find very important.

### My work at Bovi-Analytics

For my master's thesis, I developed an LSTM model to predict cows at risk of hypocalcemia using behavioral sensor data. The idea is that an improved version of the model could be used to monitor herd calcium status and identify animals at risk of transition diseases. This approach could help make proactive dairy management possible, ultimately improving animal health.
